### ISSUE TITLE
Single and Split Button Dropdown Problem

### ISSUE THREAD

**Issue by netlander** [marcoscv-work/Liferay-6.2-with-Bootstrap-3.x-theme#2]
Tried to use the button dropdowns directly from Bootstrap website but they don't seem to work.

**Comment by marcoscv-work** [comment]
You need jQuery and bootstrap.js to do it work correctly in the same way than bootstrap 2.3.2 website:
http://getbootstrap.com/2.3.2/components.html

Anyway, you have available our version (AUI/Alloy based) here:
http://liferay.github.io/alloy-bootstrap/components.html
This version is included by default, and you only need to invoke it.
