### ISSUE TITLE
Alerts not Displaying Correctly

### ISSUE THREAD

**Issue by netlander** [marcoscv-work/Liferay-6.2-with-Bootstrap-3.x-theme#3]
> alert alert-success, alert alert-info

 showing as 

> alert alert-warning

**Comment by marcoscv-work** [comment]
Not all BS styles are extended, if you need to add more classes you can add them here:

https://github.com/marcoscv-work/Liferay-6.2-with-Bootstrap-3.x-theme/blob/master/src/css/aui/bs3/_bs2_extender.scss#L39

**Comment by netlander** [comment]
I don't think it's about adding more classes, more like fixing the ones that are already there.
alert alert-success should show in green, alert alert-info should show in blue. They both show in yellow.
